//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA_TELECOME.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhonesMessage
    {
        public int Id { get; set; }
        public int PhoneId { get; set; }
        public string MessageText { get; set; }
        public string SendAt { get; set; }
    
        public virtual Phone Phone { get; set; }
    }
}
