//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA_TELECOME.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phone()
        {
            this.PhonesMessages = new HashSet<PhonesMessage>();
        }
    
        public int Id { get; set; }
        public long PhoneNumber { get; set; }
        public string PhoneNumberOwnerName { get; set; }
        public long Code { get; set; }
        public string SentAt { get; set; }
        public string CreateAt { get; set; }
        public int UserCerator { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhonesMessage> PhonesMessages { get; set; }
    }
}
